apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gke-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gke-app
  template:
    metadata:
      labels:
        app: hello-gke-app
    spec:
      containers:
        - name: hello-gke-app
          image: hello-gke-image
          ports:
            - containerPort: 80
